// <auto-generated />
using System;
using GonePhishing.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GonePhishing.Migrations
{
    [DbContext(typeof(ScanDbContext))]
    [Migration("20251110205131_typocount")]
    partial class typocount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GonePhishing.Models.DomainTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPAddresses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LookUpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanJobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId");

                    b.ToTable("DomainTasks");
                });

            modelBuilder.Entity("GonePhishing.Models.ScanJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfTypoDomains")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedDomains")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("GonePhishing.Models.DomainTask", b =>
                {
                    b.HasOne("GonePhishing.Models.ScanJob", "ScanJob")
                        .WithMany()
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });
#pragma warning restore 612, 618
        }
    }
}
